version: "3.9"

services:
  app:
    build:
      context: .
    expose:
      - 8000
    volumes:
      - static-data:/vol/web
    environment:
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASSWORD=s3cret
      - DB_HOST=db
      - DB_NAME=djangodb
      - DB_USER=dbuser
      - DB_PASSWORD=s3cret
      - DJANGO_STATIC_ROOT=/vol/web/static
      - DJANGO_MEDIA_ROOT=/vol/web/media
      - DJANGO_ALLOWED_HOSTS=localhost
      - DJANGO_CSRF_TRUSTED_ORIGINS=http://localhost:8080
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangodb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=s3cret
  
  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - static-data:/vol/staticfiles

volumes:
  db-data:
  static-data:
